import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
const DMSans = DM_Sans({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${DMSans.className} flex`}>
        <Sidebar />
        <Header />
        <NextTopLoader color="#120C18" shadow={false} />
        {children}
        <Toaster duration={3000} />
      </body>
    </html>
  );
}
