import type { Metadata } from "next";
import { DM_Sans, Poppins } from "next/font/google";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";
const DMSans = DM_Sans({ subsets: ["latin"] });
const Montserrat_font = Montserrat({ subsets: ["latin"] });
import Sidebar from "./components/Sidebar";
import Provider from "./Provider";
export const metadata: Metadata = {
  title: "KeepMe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <div className={`${DMSans.className} flex`}>
            <Sidebar />
            <Header />
            <NextTopLoader color="#120C18" shadow={false} />
            {children}
            <Toaster duration={1500} theme="system" />
          </div>
        </Provider>
      </body>
    </html>
  );
}
